export const productosCopy = {
  headerTitulo: 'Productos',
  agregar: 'Agregar producto',
  vacioTitulo: 'No tenés productos cargados',
  vacioSub: 'Agregá lo que vendés para empezar a cobrar rápido.',
  // Formulario
  nuevoTitulo: 'Nuevo producto',
  editarTitulo: 'Editar producto',
  nombreLabel: '¿Qué vendés?',
  nombrePlaceholder: 'Ej: Coca 500ml',
  precioLabel: 'Precio',
  costoLabel: 'Costo',
  costoOpcional: 'opcional',
  gananciaHint: (ganancia: string, pct: number) => `Ganás ${ganancia} · ${pct}% del precio`,
  costoMayorPrecio: 'Ojo: el costo es mayor que el precio',
  categoriaLabel: 'Categoría',
  sinCategoria: 'Sin categoría',
  nuevaCategoria: 'Nueva',
  nuevaCategoriaPh: 'Nombre de la categoría',
  crear: 'Crear',
  emojiLabel: 'Ícono (opcional)',
  guardar: 'Guardar',
  borrar: 'Borrar',
  borrarConfirm: (nombre: string) => `¿Borrar "${nombre}"?`,
  // Pantalla
  importar: 'Importar',
  gestionarCategorias: 'Categorías',
};
