export const productosCopy = {
  headerTitulo: 'Productos',
  agregar: 'Agregar producto',
  vacioTitulo: 'No tenés productos cargados',
  vacioSub: 'Agregá lo que vendés para empezar a cobrar rápido.',
  // Formulario
  nuevoTitulo: 'Nuevo producto',
  editarTitulo: 'Editar producto',
  nombreLabel: '¿Qué vendés?',
  nombrePlaceholder: 'Ej: Coca 500ml',
  precioLabel: 'Precio',
  costoLabel: 'Costo',
  costoOpcional: 'opcional',
  gananciaHint: (ganancia: string, pct: number) => `Ganás ${ganancia} · ${pct}% del precio`,
  costoMayorPrecio: 'Ojo: el costo es mayor que el precio',
  mayorLabel: 'Precio mayorista',
  mayorOpcional: 'opcional',
  mayorHint: 'Se usa cuando vendés en modo Mayorista en el POS.',
  // Stock
  stockToggle: 'Llevar stock',
  stockToggleSub: 'Descontar al vender y avisarte cuando se esté por acabar',
  stockActualLabel: 'Unidades en mano',
  stockMinLabel: 'Avisarme cuando queden',
  stockMinSufijo: 'o menos',
  stockBadge: (n: number) => `${n} u.`,
  sinStockBadge: 'sin stock',
  categoriaLabel: 'Categoría',
  sinCategoria: 'Sin categoría',
  nuevaCategoria: 'Nueva',
  nuevaCategoriaPh: 'Nombre de la categoría',
  crear: 'Crear',
  emojiLabel: 'Ícono (opcional)',
  codigoLabel: 'Código de barras',
  codigoOpcional: 'para el lector',
  codigoPlaceholder: 'Escaneá o escribí el código',
  guardar: 'Guardar',
  borrar: 'Borrar',
  borrarConfirm: (nombre: string) => `¿Borrar "${nombre}"?`,
  // Pantalla
  importar: 'Importar',
  gestionarCategorias: 'Categorías',
  agregarProductos: 'Agregar productos',

  // Hub para elegir cómo agregar
  hubTitulo: 'Agregar productos',
  hubCatalogoTit: 'Del catálogo',
  hubCatalogoSub: 'Tocá lo que vendés de una lista ya armada. Lo más rápido.',
  hubExcelTit: 'Desde Excel o foto',
  hubExcelSub: 'Subí una planilla o sacale una foto a tu lista de precios.',
  hubExcelBadge: 'IA',
  hubManualTit: 'Uno a mano',
  hubManualSub: 'Nombre, precio y costo. Para cargar de a uno.',
};
