export const posCopy = {
  headerSubtitulo: 'Tocá lo que se lleva el cliente',
  ticketVacioTitulo: 'Tocá un producto para empezar',
  ticketVacioSub: 'La cuenta se hace sola.',
  sinProductosTitulo: 'Todavía no cargaste productos',
  sinProductosSub: 'Andá a Productos y agregá lo que vendés.',
  totalLabel: 'Total',
  productosLabel: (n: number) => (n === 1 ? '1 producto' : `${n} productos`),
  verTicket: 'Ver ticket',
  vaciar: 'Vaciar',
  descuento: 'Descuento',
  sinDescuento: '—',
  redondear: 'Redondear',
  ahorro: (monto: string) => `Ahorran ${monto}`,
  cobrar: 'Cobrar',
  ventaGuardada: '¡Venta cobrada!',
  ajustes: 'Ajustes',
  // Fiar (cuenta corriente)
  fiar: 'Fiar',
  fiarTitulo: '¿A quién le fiás?',
  fiarSub: (total: string) => `Se anota ${total} en la cuenta del cliente.`,
  fiarBuscar: 'Buscar o crear cliente',
  fiarCrear: (nombre: string) => `Crear y fiar a "${nombre}"`,
  fiarDebe: (monto: string) => `debe ${monto}`,
  fiarAlDia: 'al día',
  fiarSinClientes: 'Todavía no tenés clientes. Escribí un nombre para crear el primero.',
  fiarConfirmada: '¡Fiado anotado!',
  // Editar precio en el momento (mantener presionado)
  editarPrecioTitulo: 'Editar precio',
  editarPrecioHint: 'Cambiá el precio y guardá. Queda actualizado en el catálogo.',
  guardarPrecio: 'Guardar precio',
  sinProductosCategoria: 'No hay productos en esta categoría.',
  buscarPlaceholder: 'Buscar o escanear código',
  sinResultados: 'No encontramos nada con eso.',
};
